//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "forum_presets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub preset_id: String,
    pub title_welcome: String,
    pub total_threads: i32,
    pub total_posts: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

pub type ForumPreset = Model;
