//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7
/// Copyright (c) 2023, Sean McNamara <smcnam@gmail.com>.
/// All code in this repository is disjunctively licensed under [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/) and [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0).
/// Direct dependencies are believed to be under a license which allows downstream code to have these licenses.
pub mod prelude;

pub mod category_names;
pub mod forum_posts;
pub mod forum_presets;
pub mod forum_threads;
pub mod images;
pub mod subforums;
pub mod applications;
