//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7
/// Copyright (c) 2023, Sean McNamara <smcnam@gmail.com>.
/// All code in this repository is disjunctively licensed under [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/) and [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0).
/// Direct dependencies are believed to be under a license which allows downstream code to have these licenses.

pub use super::category_names::Entity as CategoryNames;
pub use super::forum_posts::Entity as ForumPosts;
pub use super::forum_presets::Entity as ForumPresets;
pub use super::forum_threads::Entity as ForumThreads;
pub use super::images::Entity as Images;
pub use super::subforums::Entity as Subforums;
