//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

pub use super::category_names::Entity as CategoryNames;
pub use super::forum_posts::Entity as ForumPosts;
pub use super::forum_presets::Entity as ForumPresets;
pub use super::forum_threads::Entity as ForumThreads;
pub use super::images::Entity as Images;
pub use super::subforums::Entity as Subforums;
